### ISSUE TITLE
Fail gracefully when command doesn't exist

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#152]
```
When a command fails, we should fail gracefully like git does

(base) ben@surface:~/test$ git gud foo
Traceback (most recent call last):
  File "/home/ben/anaconda3/bin/git-gud", line 11, in <module>
    load_entry_point('git-gud', 'console_scripts', 'git-gud')()
  File "/home/ben/git-gud/gitgud/__main__.py", line 416, in main
    GitGud().parse()
  File "/home/ben/git-gud/gitgud/__main__.py", line 91, in __init__
    show_parser.add_argument('param', metavar='tree', help='Required for command.')
NameError: name 'show_parser' is not defined
```
Here's how git does it:
```
(base) ben@surface:~/test$ git asdf
git: 'asdf' is not a git command. See 'git --help'.

The most similar command is
        add
```
How about we do:
```
(base) ben@surface:~/test$ git gud asdf
git gud: 'asdf' is not a git command. See 'git gud --help'.
```

**Comment by benthayer** [comment]
@sahansk2

**Comment by benthayer** [comment]
#182 See 182 for an example

**Comment by benthayer** [comment]
Not sure when this was fixed
