### ISSUE TITLE
Check error codes in test suites

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#197]
When commands fail, they should fail with status code 1, which could help us make sure users are never seeing an error that's coming from python.

**Comment by benthayer** [comment]
> We currently do nothing to test that the commands the user sees don't have issues.
> 
> If we have a bad reference to a variable in a method that is only called by users, we may have an undefined variable that isn't covered in the test cases. We should make sure that users will never see things like `NameError: name 'passed_path' is not defined`

See #171

**Comment by sahansk2** [comment]
@benthayer Hoop v2

**Comment by sahansk2** [comment]
@benthayer Hoop

**Comment by sahansk2** [comment]
@benthayer Hmm...just to make sure, would you like some sort of error handling so that the error is hidden from the user unless they run `git gud error` explicitly (for debug purposes)? Something like

> Oops! Git Gud ran into a problem. Please try your command again. If the problem persists, please run `git gud issues` to open our GitHub, and create an issue with the output of `git gud error` so that we can try to help you!

, maybe?

Because as it is, if Python throws an error with a traceback, the default error code is 1:
```
sahan@sahan-Lenovo-YOGA-C930-ubuntu:test$ git gud test
Traceback (most recent call last):
  File "/home/sahan/.local/bin/git-gud", line 7, in <module>
    from gitgud.__main__ import main
  File "/home/sahan/.local/lib/python3.6/site-packages/gitgud/__main__.py", line 11, in <module>
    from gitgud import operations
  File "/home/sahan/.local/lib/python3.6/site-packages/gitgud/operations.py", line 11, in <module>
    from gitgud.skills.user_messages import mock_simulate, print_info
  File "/home/sahan/.local/lib/python3.6/site-packages/gitgud/skills/__init__.py", line 1, in <module>
    from gitgud.skills.intro import skill as intro_skill
  File "/home/sahan/.local/lib/python3.6/site-packages/gitgud/skills/intro/__init__.py", line 11
    this is super bad code 
                    ^
SyntaxError: invalid syntax
sahan@sahan-Lenovo-YOGA-C930-ubuntu:test$ echo $?
1
```

**Comment by benthayer** [comment]
The bigger part of this issue is adding the tests, but yes, we also don't want the user to see crazy errors like that. We could pickle the error and `git gud error` would read that file and print out the stack trace and maybe some other info.

**Comment by sahansk2** [comment]
@benthayer I don't think we need to `pickle` the error, since the stack trace is only useful as text for us (and so, `pickle` seems overkill). We could always just output to two files, `.git/gud/error.txt` and `.git/gud/logs/hh:mm-m-d-y.txt` with `error.txt` holding the content of the most recent log. `git gud error` would print out `error.txt`.

I think we should try to make use of the [`logging`](https://docs.python.org/3/library/logging.html) module, since it has [support for writing to files with extra information](https://docs.python.org/3/howto/logging.html#logging-to-a-file).

**Comment by sahansk2** [comment]
@benthayer I'm going to create a new issue for making sure that the user doesn't see errors. I think this is distinct from directly testing the user commands.
